/*
 * tapenade_cost_driver.c
 *
 * E8: the first calibration gradient.  Tapenade tangent of a scalar cost
 * function with respect to two DSBM calibration parameters, the lateral
 * rate constant k_lf (m/h) and the percolation limiter (-).
 *
 * Synthetic-truth design: "observed" hourly lateral flow and percolation
 * are generated by the same model at known parameters
 *     k_lf_true = 2.0e-3 m/h,  perc_limiter_true = 0.5,  fixed 4 substeps,
 * over the first year (8760 h) of forcing/rain_pet_example.csv.  The cost
 * function (see tapenade_cost_primal.c) is the sum of (1 - NSE) for the
 * two series, so it is exactly 0 at the truth when the simulation uses
 * fixed 4 substeps.
 *
 *   E8a  Gradient check at a point away from the truth: AD against
 *        centered finite differences (FD), for fixed 4, 12 and 24
 *        substeps.  Also how much the gradient depends on the substep
 *        count.
 *
 *   E8b  One-parameter sweeps through the truth (k_lf with
 *        perc_limiter at truth, and perc_limiter with k_lf at truth), for
 *        fixed 4 and 12 substeps: cost, AD derivative, FD agreement, and
 *        where the derivative changes sign.  A gradient-based calibration
 *        needs one sign change, at the minimum.
 *
 *   E8c  Calibration by BFGS quasi-Newton descent using only the AD
 *        gradient, in u = (ln k_lf, perc_limiter), from two starting
 *        points, simulated with fixed 4 substeps (the setting used for
 *        the observations: exact recovery expected) and with fixed 12
 *        (small model mismatch: recovery near the truth expected).
 *
 * Usage:
 *   tapenade_cost_derivative_test  output_directory  forcing_csv_file  [experiments]
 *   experiments: digit string, default "abc"; letters a, b, c select E8a-E8c.
 *
 * Terminology: soil moisture; discs; cost function.
 * ASCII only.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#include "soil_data_types.h"
#include "soil_helpers.h"


/* ---- functions in tapenade_cost_primal.c and the adapter ---- */

double cost_experiment_phi_sat_cm(void);

void dsbm_cost_from_params(double klf_m_per_h,
                           double perc_limiter_0_to_1,
                           const double *theta_in,
                           int n_steps,
                           int n_sub_setting,
                           const double *rain_mm_per_h,
                           const double *pet_mm_per_h,
                           const double *observed_lateral_m,
                           const double *observed_percolation_m,
                           double sst_lateral_m2,
                           double sst_percolation_m2,
                           double *cost_function_value);

void dsbm_series_from_params(double klf_m_per_h,
                             double perc_limiter_0_to_1,
                             const double *theta_in,
                             int n_steps,
                             int n_sub_setting,
                             const double *rain_mm_per_h,
                             const double *pet_mm_per_h,
                             double *lateral_series_m,
                             double *percolation_series_m);

void cost_tangent_from_tapenade(double klf_m_per_h,
                                double perc_limiter_0_to_1,
                                double seed_klf,
                                double seed_perc_limiter,
                                const double *theta_in,
                                int n_steps,
                                int n_sub_setting,
                                const double *rain_mm_per_h,
                                const double *pet_mm_per_h,
                                const double *observed_lateral_m,
                                const double *observed_percolation_m,
                                double sst_lateral_m2,
                                double sst_percolation_m2,
                                double *cost_function_value,
                                double *directional_derivative_of_cost);


/* ---- experiment constants ---- */

#define N_HOURS                     8760
#define KLF_TRUE_M_PER_H            2.0e-3
#define PERC_LIMITER_TRUE           0.5
#define N_SUB_FOR_OBSERVATIONS      4
#define PERC_LIMITER_LOWER_BOUND    0.01
#define PERC_LIMITER_UPPER_BOUND    0.999
#define KLF_LOWER_BOUND_M_PER_H     1.0e-5
#define KLF_UPPER_BOUND_M_PER_H     1.0

static const double disc_center_depth_m[NDISC] = {0.05, 0.25, 0.70, 1.50};


/* ---- the calibration problem, set up once ---- */

typedef struct {
    double theta_in[NDISC];
    int n_steps;
    double rain_mm_per_h[N_HOURS];
    double pet_mm_per_h[N_HOURS];
    double observed_lateral_m[N_HOURS];
    double observed_percolation_m[N_HOURS];
    double sst_lateral_m2;
    double sst_percolation_m2;
} CalibrationProblem;

static CalibrationProblem problem;


static int read_forcing_csv(const char *path, int n_wanted,
                            double *rain_mm_per_h, double *pet_mm_per_h)
{
    FILE *fp;
    char line[512];
    int n_read = 0;

    fp = fopen(path, "r");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: cannot open forcing file %s\n", path);
        return -1;
    }
    if (fgets(line, sizeof(line), fp) == NULL) {
        fclose(fp);
        return -1;
    }
    while (n_read < n_wanted && fgets(line, sizeof(line), fp) != NULL) {
        char *first_comma = strchr(line, ',');
        double rain_value;
        double pet_value;

        if (first_comma == NULL) continue;
        if (sscanf(first_comma + 1, "%lf,%lf", &rain_value, &pet_value) != 2) continue;
        rain_mm_per_h[n_read] = rain_value;
        pet_mm_per_h[n_read] = pet_value;
        n_read++;
    }
    fclose(fp);
    return n_read;
}

static double sum_of_squared_deviations(const double *series, int n)
{
    double mean_value = 0.0;
    double sum_squares = 0.0;
    int i;

    for (i = 0; i < n; i++) mean_value = mean_value + series[i];
    mean_value = mean_value / (double)n;
    for (i = 0; i < n; i++) {
        double deviation = series[i] - mean_value;
        sum_squares = sum_squares + deviation * deviation;
    }
    return sum_squares;
}

static int set_up_problem(const char *forcing_path)
{
    double water_table_depth_m;

    problem.n_steps = read_forcing_csv(forcing_path, N_HOURS,
                                       problem.rain_mm_per_h, problem.pet_mm_per_h);
    if (problem.n_steps < N_HOURS) {
        fprintf(stderr, "ERROR: need %d forcing hours, read %d\n", N_HOURS, problem.n_steps);
        return -1;
    }

    initialize_hydrostatic_from_storage(2.0, 0.439, cost_experiment_phi_sat_cm(), 4.05,
                                        disc_center_depth_m, 0.7843498367003,
                                        &water_table_depth_m, problem.theta_in);

    dsbm_series_from_params(KLF_TRUE_M_PER_H, PERC_LIMITER_TRUE, problem.theta_in,
                            problem.n_steps, N_SUB_FOR_OBSERVATIONS,
                            problem.rain_mm_per_h, problem.pet_mm_per_h,
                            problem.observed_lateral_m, problem.observed_percolation_m);

    problem.sst_lateral_m2 = sum_of_squared_deviations(problem.observed_lateral_m, problem.n_steps);
    problem.sst_percolation_m2 = sum_of_squared_deviations(problem.observed_percolation_m, problem.n_steps);
    return 0;
}


/* ---- cost and gradient ---- */

static double cost_primal(double klf, double perc_limiter, int n_sub_setting)
{
    double cost;

    dsbm_cost_from_params(klf, perc_limiter, problem.theta_in, problem.n_steps,
                          n_sub_setting, problem.rain_mm_per_h, problem.pet_mm_per_h,
                          problem.observed_lateral_m, problem.observed_percolation_m,
                          problem.sst_lateral_m2, problem.sst_percolation_m2, &cost);
    return cost;
}

/* AD gradient: two tangent calls, seeds (1,0) and (0,1). Returns the cost. */
static double cost_gradient_ad(double klf, double perc_limiter, int n_sub_setting,
                               double *d_cost_d_klf, double *d_cost_d_perc)
{
    double cost;

    cost_tangent_from_tapenade(klf, perc_limiter, 1.0, 0.0, problem.theta_in,
                               problem.n_steps, n_sub_setting,
                               problem.rain_mm_per_h, problem.pet_mm_per_h,
                               problem.observed_lateral_m, problem.observed_percolation_m,
                               problem.sst_lateral_m2, problem.sst_percolation_m2,
                               &cost, d_cost_d_klf);
    cost_tangent_from_tapenade(klf, perc_limiter, 0.0, 1.0, problem.theta_in,
                               problem.n_steps, n_sub_setting,
                               problem.rain_mm_per_h, problem.pet_mm_per_h,
                               problem.observed_lateral_m, problem.observed_percolation_m,
                               problem.sst_lateral_m2, problem.sst_percolation_m2,
                               &cost, d_cost_d_perc);
    return cost;
}

static double relative_difference(double value, double reference)
{
    if (fabs(reference) > 1.0e-300) return (value - reference) / fabs(reference);
    return value - reference;
}

static FILE *open_csv(const char *output_dir, const char *file_name)
{
    char path[1024];
    FILE *fp;

    snprintf(path, sizeof(path), "%s/%s", output_dir, file_name);
    fp = fopen(path, "w");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: cannot open %s\n", path);
        exit(1);
    }
    return fp;
}


/* ---- E8a gradient check ---- */

static void experiment_8a_gradient_check(void)
{
    const double klf = 5.0e-4;
    const double perc_limiter = 0.8;
    const int n_sub_list[3] = {4, 12, 24};
    const double relative_eps[3] = {1.0e-3, 1.0e-5, 1.0e-7};
    double ad_reference_klf = 0.0;
    double ad_reference_perc = 0.0;

    printf("====================================================================\n");
    printf("E8a  GRADIENT CHECK at k_lf = %.1e m/h, perc_limiter = %.2f\n", klf, perc_limiter);
    printf("     (truth: k_lf = %.1e m/h, perc_limiter = %.2f)\n", KLF_TRUE_M_PER_H, PERC_LIMITER_TRUE);
    printf("====================================================================\n");

    for (int i_n = 0; i_n < 3; i_n++) {
        int n_sub = n_sub_list[i_n];
        double d_cost_d_klf;
        double d_cost_d_perc;
        double cost_ad;
        double cost_check;

        cost_ad = cost_gradient_ad(klf, perc_limiter, n_sub, &d_cost_d_klf, &d_cost_d_perc);
        cost_check = cost_primal(klf, perc_limiter, n_sub);
        if (i_n == 1) {
            ad_reference_klf = d_cost_d_klf;
            ad_reference_perc = d_cost_d_perc;
        }

        printf("\n--- fixed %d substeps ---\n", n_sub);
        printf("cost = %.12e  (primal %.12e, rel diff %.1e)\n", cost_ad, cost_check,
               relative_difference(cost_check, cost_ad));
        printf("AD  dcost/dk_lf          = %+.12e  (1/(m/h))\n", d_cost_d_klf);
        printf("AD  dcost/dperc_limiter  = %+.12e\n", d_cost_d_perc);
        printf("%10s %22s %10s %22s %10s\n", "FD rel h", "FD dcost/dk_lf", "rel diff",
               "FD dcost/dperc", "rel diff");
        for (int i_e = 0; i_e < 3; i_e++) {
            double hk = klf * relative_eps[i_e];
            double hp = perc_limiter * relative_eps[i_e];
            double fd_klf = (cost_primal(klf + hk, perc_limiter, n_sub) -
                             cost_primal(klf - hk, perc_limiter, n_sub)) / (2.0 * hk);
            double fd_perc = (cost_primal(klf, perc_limiter + hp, n_sub) -
                              cost_primal(klf, perc_limiter - hp, n_sub)) / (2.0 * hp);
            printf("%10.0e %+22.12e %10.2e %+22.12e %10.2e\n", relative_eps[i_e],
                   fd_klf, relative_difference(fd_klf, d_cost_d_klf),
                   fd_perc, relative_difference(fd_perc, d_cost_d_perc));
        }
    }

    {
        double d_cost_d_klf;
        double d_cost_d_perc;

        printf("\nGradient dependence on substep count (relative to fixed 12):\n");
        for (int i_n = 0; i_n < 3; i_n++) {
            cost_gradient_ad(klf, perc_limiter, n_sub_list[i_n], &d_cost_d_klf, &d_cost_d_perc);
            printf("   fixed %2d:  dcost/dk_lf %+9.2e   dcost/dperc %+9.2e\n", n_sub_list[i_n],
                   relative_difference(d_cost_d_klf, ad_reference_klf),
                   relative_difference(d_cost_d_perc, ad_reference_perc));
        }
    }
}


/* ---- E8b one-parameter sweeps through the truth ---- */

static void sweep_one_parameter(const char *output_dir, int sweep_klf, int n_sub)
{
    const int n_points = 61;
    char csv_name[128];
    int n_sign_changes = 0;
    double previous_derivative = 0.0;
    double previous_value = 0.0;
    double worst_fd_rel = 0.0;
    double worst_fd_at = 0.0;
    FILE *fp;

    if (sweep_klf) {
        snprintf(csv_name, sizeof(csv_name), "e8b_sweep_klf_nsub%d.csv", n_sub);
    } else {
        snprintf(csv_name, sizeof(csv_name), "e8b_sweep_perc_nsub%d.csv", n_sub);
    }
    fp = open_csv(output_dir, csv_name);
    fprintf(fp, "parameter_value,cost,AD_derivative,FD_derivative,rel_diff\n");

    if (sweep_klf) {
        printf("\n--- k_lf sweep, perc_limiter = %.2f (truth), fixed %d substeps ---\n",
               PERC_LIMITER_TRUE, n_sub);
    } else {
        printf("\n--- perc_limiter sweep, k_lf = %.1e (truth), fixed %d substeps ---\n",
               KLF_TRUE_M_PER_H, n_sub);
    }
    printf("%14s %16s %18s %10s\n", "parameter", "cost", "AD dcost/dparam", "FD-AD rel");

    for (int i_pt = 0; i_pt < n_points; i_pt++) {
        double klf;
        double perc_limiter;
        double value;
        double d_cost_d_klf;
        double d_cost_d_perc;
        double derivative;
        double h;
        double fd;
        double cost;
        double rel;

        if (sweep_klf) {
            klf = pow(10.0, log10(2.0e-4) + 2.0 * (double)i_pt / (double)(n_points - 1));
            perc_limiter = PERC_LIMITER_TRUE;
            value = klf;
        } else {
            klf = KLF_TRUE_M_PER_H;
            perc_limiter = 0.05 + 0.90 * (double)i_pt / (double)(n_points - 1);
            value = perc_limiter;
        }

        cost = cost_gradient_ad(klf, perc_limiter, n_sub, &d_cost_d_klf, &d_cost_d_perc);
        if (sweep_klf) {
            derivative = d_cost_d_klf;
            h = klf * 1.0e-5;
            fd = (cost_primal(klf + h, perc_limiter, n_sub) -
                  cost_primal(klf - h, perc_limiter, n_sub)) / (2.0 * h);
        } else {
            derivative = d_cost_d_perc;
            h = perc_limiter * 1.0e-5;
            fd = (cost_primal(klf, perc_limiter + h, n_sub) -
                  cost_primal(klf, perc_limiter - h, n_sub)) / (2.0 * h);
        }
        rel = relative_difference(fd, derivative);
        if (fabs(rel) > worst_fd_rel && fabs(derivative) > 1.0e-6) {
            worst_fd_rel = fabs(rel);
            worst_fd_at = value;
        }

        if (i_pt > 0 && derivative * previous_derivative < 0.0) {
            n_sign_changes++;
            printf("   derivative changes sign between %.6e and %.6e\n", previous_value, value);
        }
        if (i_pt % 6 == 0) {
            if (fabs(derivative) > 1.0e-6) {
                printf("%14.6e %16.8e %+18.8e %10.2e\n", value, cost, derivative, rel);
            } else {
                printf("%14.6e %16.8e %+18.8e %10s\n", value, cost, derivative, "(minimum)");
            }
        }
        fprintf(fp, "%.12e,%.12e,%.12e,%.12e,%.4e\n", value, cost, derivative, fd, rel);
        previous_derivative = derivative;
        previous_value = value;
    }
    fclose(fp);
    printf("sign changes: %d   worst |FD-AD| rel (|AD| > 1e-6) = %.2e at %.4e\n",
           n_sign_changes, worst_fd_rel, worst_fd_at);
}

static void experiment_8b_sweeps(const char *output_dir)
{
    printf("\n====================================================================\n");
    printf("E8b  ONE-PARAMETER SWEEPS THROUGH THE TRUTH (every 6th point shown)\n");
    printf("====================================================================\n");
    sweep_one_parameter(output_dir, 1, 4);
    sweep_one_parameter(output_dir, 1, 12);
    sweep_one_parameter(output_dir, 0, 4);
    sweep_one_parameter(output_dir, 0, 12);
}


/* ---- E8c BFGS calibration with the AD gradient ---- */

static void clamp_parameters(double *log_klf, double *perc_limiter)
{
    if (*log_klf < log(KLF_LOWER_BOUND_M_PER_H)) *log_klf = log(KLF_LOWER_BOUND_M_PER_H);
    if (*log_klf > log(KLF_UPPER_BOUND_M_PER_H)) *log_klf = log(KLF_UPPER_BOUND_M_PER_H);
    if (*perc_limiter < PERC_LIMITER_LOWER_BOUND) *perc_limiter = PERC_LIMITER_LOWER_BOUND;
    if (*perc_limiter > PERC_LIMITER_UPPER_BOUND) *perc_limiter = PERC_LIMITER_UPPER_BOUND;
}

/* cost and gradient in u = (ln k_lf, perc_limiter) */
static double cost_and_gradient_u(const double *u, int n_sub, double *gradient_u)
{
    double klf = exp(u[0]);
    double d_cost_d_klf;
    double d_cost_d_perc;
    double cost;

    cost = cost_gradient_ad(klf, u[1], n_sub, &d_cost_d_klf, &d_cost_d_perc);
    gradient_u[0] = klf * d_cost_d_klf;
    gradient_u[1] = d_cost_d_perc;
    return cost;
}

static void calibrate_bfgs(double klf_start, double perc_start, int n_sub)
{
    const int max_iterations = 60;
    double u[2];
    double gradient[2];
    double inverse_hessian[2][2] = {{1.0, 0.0}, {0.0, 1.0}};
    double cost;
    int n_cost_evaluations = 0;

    u[0] = log(klf_start);
    u[1] = perc_start;
    cost = cost_and_gradient_u(u, n_sub, gradient);
    n_cost_evaluations++;

    printf("\n--- start k_lf = %.2e m/h, perc_limiter = %.2f, fixed %d substeps ---\n",
           klf_start, perc_start, n_sub);
    printf("%4s %16s %14s %12s %12s %6s\n", "iter", "cost", "k_lf (m/h)",
           "perc_limiter", "|gradient|", "evals");
    printf("%4d %16.8e %14.6e %12.6f %12.3e %6d\n", 0, cost, exp(u[0]), u[1],
           sqrt(gradient[0] * gradient[0] + gradient[1] * gradient[1]), n_cost_evaluations);

    for (int iteration = 1; iteration <= max_iterations; iteration++) {
        double direction[2];
        double u_new[2];
        double gradient_new[2];
        double cost_new = 0.0;
        double step_length = 1.0;
        double slope;
        int accepted = 0;

        direction[0] = -(inverse_hessian[0][0] * gradient[0] + inverse_hessian[0][1] * gradient[1]);
        direction[1] = -(inverse_hessian[1][0] * gradient[0] + inverse_hessian[1][1] * gradient[1]);
        slope = direction[0] * gradient[0] + direction[1] * gradient[1];
        if (slope >= 0.0) {
            /* not a descent direction: reset to steepest descent */
            inverse_hessian[0][0] = 1.0;
            inverse_hessian[0][1] = 0.0;
            inverse_hessian[1][0] = 0.0;
            inverse_hessian[1][1] = 1.0;
            direction[0] = -gradient[0];
            direction[1] = -gradient[1];
            slope = direction[0] * gradient[0] + direction[1] * gradient[1];
        }

        /* backtracking line search with Armijo condition */
        for (int i_ls = 0; i_ls < 40; i_ls++) {
            u_new[0] = u[0] + step_length * direction[0];
            u_new[1] = u[1] + step_length * direction[1];
            clamp_parameters(&u_new[0], &u_new[1]);
            cost_new = cost_primal(exp(u_new[0]), u_new[1], n_sub);
            n_cost_evaluations++;
            if (cost_new <= cost + 1.0e-4 * step_length * slope) {
                accepted = 1;
                break;
            }
            step_length = 0.5 * step_length;
        }
        if (!accepted) {
            printf("line search failed at iteration %d\n", iteration);
            break;
        }

        cost_new = cost_and_gradient_u(u_new, n_sub, gradient_new);
        n_cost_evaluations++;
        {
            /* stop when the accepted step no longer reduces the cost
               meaningfully (roundoff floor of the cost function) */
            double relative_decrease = (cost - cost_new) / cost;
            if (relative_decrease < 1.0e-12) {
                u[0] = u_new[0];
                u[1] = u_new[1];
                cost = cost_new;
                printf("%4d %16.8e %14.6e %12.6f %12.3e %6d  (cost decrease < 1e-12 relative: converged)\n",
                       iteration, cost, exp(u[0]), u[1],
                       sqrt(gradient_new[0] * gradient_new[0] + gradient_new[1] * gradient_new[1]),
                       n_cost_evaluations);
                break;
            }
        }

        /* BFGS update of the inverse Hessian */
        {
            double s[2];
            double y[2];
            double sy;

            s[0] = u_new[0] - u[0];
            s[1] = u_new[1] - u[1];
            y[0] = gradient_new[0] - gradient[0];
            y[1] = gradient_new[1] - gradient[1];
            sy = s[0] * y[0] + s[1] * y[1];
            if (sy > 1.0e-300) {
                double Hy[2];
                double yHy;
                double rho = 1.0 / sy;

                Hy[0] = inverse_hessian[0][0] * y[0] + inverse_hessian[0][1] * y[1];
                Hy[1] = inverse_hessian[1][0] * y[0] + inverse_hessian[1][1] * y[1];
                yHy = y[0] * Hy[0] + y[1] * Hy[1];
                for (int r = 0; r < 2; r++) {
                    for (int c = 0; c < 2; c++) {
                        inverse_hessian[r][c] = inverse_hessian[r][c]
                            - rho * (Hy[r] * s[c] + s[r] * Hy[c])
                            + (rho * rho * yHy + rho) * s[r] * s[c];
                    }
                }
            }
        }

        u[0] = u_new[0];
        u[1] = u_new[1];
        gradient[0] = gradient_new[0];
        gradient[1] = gradient_new[1];
        cost = cost_new;

        printf("%4d %16.8e %14.6e %12.6f %12.3e %6d\n", iteration, cost, exp(u[0]), u[1],
               sqrt(gradient[0] * gradient[0] + gradient[1] * gradient[1]), n_cost_evaluations);

        if (cost < 1.0e-20) break;
        if (sqrt(gradient[0] * gradient[0] + gradient[1] * gradient[1]) < 1.0e-12) break;
    }
    printf("result: k_lf = %.8e m/h (truth %.1e, rel err %.2e), perc_limiter = %.8f (truth %.2f, rel err %.2e)\n",
           exp(u[0]), KLF_TRUE_M_PER_H, relative_difference(exp(u[0]), KLF_TRUE_M_PER_H),
           u[1], PERC_LIMITER_TRUE, relative_difference(u[1], PERC_LIMITER_TRUE));
}

static void experiment_8c_calibration(void)
{
    printf("\n====================================================================\n");
    printf("E8c  CALIBRATION BY BFGS WITH THE AD GRADIENT, u = (ln k_lf, perc_limiter)\n");
    printf("     observations made with fixed %d substeps\n", N_SUB_FOR_OBSERVATIONS);
    printf("====================================================================\n");
    calibrate_bfgs(5.0e-4, 0.80, 4);
    calibrate_bfgs(1.0e-2, 0.20, 4);
    calibrate_bfgs(5.0e-4, 0.80, 12);
}


/* ---- consistency check and main ---- */

static int primal_and_tangent_agree(void)
{
    double d1;
    double d2;
    double cost_tangent = cost_gradient_ad(1.0e-3, 0.7, 4, &d1, &d2);
    double cost_check = cost_primal(1.0e-3, 0.7, 4);

    if (fabs(cost_tangent - cost_check) > 1.0e-12 * fabs(cost_check)) {
        printf("CONSISTENCY FAILURE: primal cost %.17e, tangent cost %.17e\n",
               cost_check, cost_tangent);
        printf("libsoil.a is probably stale.  Rebuild with: make veryclean ; make\n");
        return 0;
    }
    return 1;
}

int main(int argc, char **argv)
{
    const char *output_dir = ".";
    const char *forcing_path = "forcing/rain_pet_example.csv";
    const char *experiments = "abc";

    if (argc > 1) output_dir = argv[1];
    if (argc > 2) forcing_path = argv[2];
    if (argc > 3) experiments = argv[3];

    if (set_up_problem(forcing_path) != 0) return 1;
    if (!primal_and_tangent_agree()) return 2;
    printf("Consistency check passed: primal and tangent cost values agree.\n");
    {
        double total_lateral_m = 0.0;
        double total_percolation_m = 0.0;

        for (int i_step = 0; i_step < problem.n_steps; i_step++) {
            total_lateral_m = total_lateral_m + problem.observed_lateral_m[i_step];
            total_percolation_m = total_percolation_m + problem.observed_percolation_m[i_step];
        }
        printf("Problem: %d hours; observed totals: lateral %.6f m, percolation %.6f m\n",
               problem.n_steps, total_lateral_m, total_percolation_m);
    }

    if (strchr(experiments, 'a') != NULL) experiment_8a_gradient_check();
    if (strchr(experiments, 'b') != NULL) experiment_8b_sweeps(output_dir);
    if (strchr(experiments, 'c') != NULL) experiment_8c_calibration();
    return 0;
}
