#include <stdio.h>

#include "soil_data_types.h"

/*
 * Tapenade's generated soil_data_types_d.h repeats the primal typedefs,
 * so it cannot be included together with the production soil_data_types.h.
 * This is the tangent type Tapenade generated for passive SoilStateIn.
 */
typedef struct {
    double psi_in[NDISC];
    double K_in[NDISC];
} SoilStateIn_diff;

/*
 * Generated by Tapenade from tapenade_dsbm_test.c.
 * K_sat_cm_per_h is the only active input.  SoilStateIn is held fixed,
 * so its tangent state is zero.
 */
void dsbm_percolation_from_ksat_d(double K_sat_cm_per_h,
                                  double K_sat_cm_per_hd,
                                  const SoilStateIn *sin,
                                  const SoilStateIn_diff *sind,
                                  double *percolation_to_gw_m,
                                  double *percolation_to_gw_md);

void dsbm_percolation_from_ksat(double K_sat_cm_per_h,
                                const SoilStateIn *sin,
                                double *percolation_to_gw_m);

void initialize_baseline_state_for_driver(SoilStateIn *sin);

int main(void)
{
    const double K0 = 1.2168;
    const double relative_eps[] = {
        1.0e-2, 1.0e-3, 1.0e-4, 1.0e-5, 1.0e-6
    };
    const int n_eps =
        (int)(sizeof(relative_eps) / sizeof(relative_eps[0]));

    SoilStateIn sin;
    SoilStateIn_diff sind = {0};
    double q_ad;
    double dq_dK_ad;

    initialize_baseline_state_for_driver(&sin);

    dsbm_percolation_from_ksat_d(
        K0, 1.0, &sin, &sind, &q_ad, &dq_dK_ad);

    printf("K_sat_cm_per_h = %.17g\n", K0);
    printf("q_perc_m       = %.17g\n", q_ad);
    printf("AD dq/dK       = %.17g m/(cm/h)\n\n", dq_dK_ad);

    printf("# rel_eps,abs_eps,FD_dq_dK,relative_difference_from_AD\n");

    for (int i = 0; i < n_eps; i++) {
        const double eps = K0 * relative_eps[i];
        double q_plus;
        double q_minus;
        double dq_dK_fd;
        double relative_difference;

        dsbm_percolation_from_ksat(K0 + eps, &sin, &q_plus);
        dsbm_percolation_from_ksat(K0 - eps, &sin, &q_minus);

        dq_dK_fd = (q_plus - q_minus) / (2.0 * eps);

        if (dq_dK_ad != 0.0)
            relative_difference =
                (dq_dK_fd - dq_dK_ad) / dq_dK_ad;
        else
            relative_difference = 0.0;

        printf("%.1e,%.17g,%.17g,%.17g\n",
               relative_eps[i], eps, dq_dK_fd,
               relative_difference);
    }

    return 0;
}
