/*
 * noahmp_soilwater_stateless.c
 *
 * Compact C99 translation of the unfrozen Noah-MP soil-moisture Richards
 * solver used for a controlled comparison with the DSBM kernel.
 *
 * The translated numerical core follows the supplied Noah-MP routines:
 *   WDFCND1 -> SRT -> SSTEP -> ROSR12
 *
 * Deliberate comparison-wrapper choices:
 *   - no soil ice: FCR = 0 and SMC = SH2O = theta
 *   - incident rainfall is supplied directly as PDDUM (m/s); saturation
 *     excess generated by SSTEP is returned as rain excess
 *   - bottom drainage uses WCND(bottom) multiplied by perc_limiter_0_to_1;
 *     optional apply_fc_perc_threshold restricts drainage to water above theta_fc;
 *     this uses the existing DSBM parameter as the Noah-MP free-drainage
 *     SLOPE multiplier
 *   - transpiration demand uses the same DSBM PET/root-zone stress rule
 *     so that the experiment isolates the vertical soil-water solver
 *   - no lateral Nash removal in this comparison kernel
 *
 * Noah-MP uses SI seconds internally.  Public driver quantities retain the
 * existing DSBM interface units.
 */

#include <math.h>
#include <stdio.h>
#include <string.h>

#include "noahmp_soilwater_stateless.h"

#ifndef THETA_MIN
#define THETA_MIN 1.0e-03
#endif

static double storage_sum(const double theta[NDISC], const double dz[NDISC], int ndisc)
{
    double storage_m = 0.0;
    int k;
    for (k = 0; k < ndisc; k++) storage_m += theta[k] * dz[k];
    return storage_m;
}

/* Noah-MP WDFCND1, unfrozen (FCR=0).
 *
 * The supplied Noah-MP source receives DWSAT as a parameter rather than
 * constructing it in WDFCND1.  For this controlled CH comparison we derive
 * saturated diffusivity from the same Clapp-Hornberger relations used by
 * DSBM: D = K * |d psi / d theta|, hence
 * DWSAT = b * Ksat * phi_sat / theta_sat.
 */
static void noahmp_wdfcnd1(const SoilParameters *par, double theta,
                           double *wdf_m2_per_s, double *wcnd_m_per_s)
{
    double factr;
    double ksat_m_per_s;
    double phi_sat_m;
    double dwsat_m2_per_s;

    factr = theta / par->theta_sat;
    if (factr < 0.01) factr = 0.01;

    ksat_m_per_s = (par->K_sat_cm_per_h / 100.0) / 3600.0;
    phi_sat_m = par->phi_sat_cm / 100.0;
    dwsat_m2_per_s = par->b_exp * ksat_m_per_s * phi_sat_m / par->theta_sat;

    *wdf_m2_per_s = dwsat_m2_per_s * pow(factr, par->b_exp + 2.0);
    *wcnd_m_per_s = ksat_m_per_s * pow(factr, 2.0 * par->b_exp + 3.0);
}

/* Direct C translation of ROSR12 for soil layers only (NTOP=1, NSNOW=0).
 * On return p[] contains the solved increment, matching the Fortran use of
 * CI after CALL ROSR12(CI,AI,BI,CIIN,RHSTTIN,RHSTT,...).
 */
static int noahmp_rosr12(double p[NDISC], const double a[NDISC],
                         const double b[NDISC], const double c_in[NDISC],
                         const double d[NDISC], int ndisc)
{
    double delta[NDISC];
    double c[NDISC];
    int k;

    for (k = 0; k < ndisc; k++) c[k] = c_in[k];
    c[ndisc - 1] = 0.0;

    if (fabs(b[0]) < 1.0e-30) return 1;
    p[0] = -c[0] / b[0];
    delta[0] = d[0] / b[0];

    for (k = 1; k < ndisc; k++) {
        double denom = b[k] + a[k] * p[k - 1];
        if (fabs(denom) < 1.0e-30) return 1;
        p[k] = -c[k] / denom;
        delta[k] = (d[k] - a[k] * delta[k - 1]) / denom;
    }

    p[ndisc - 1] = delta[ndisc - 1];
    for (k = ndisc - 2; k >= 0; k--) p[k] = p[k] * p[k + 1] + delta[k];

    return 0;
}

/* Translation of SRT for the unfrozen/free-drainage comparison path. */
static void noahmp_srt(const SoilControl *ctrl,
                       const SoilGeometry *geom, const SoilParameters *par,
                       const double theta[NDISC], const double etrani_m_per_s[NDISC],
                       double pddum_m_per_s, double qseva_m_per_s,
                       double dtfine_s, int ndisc,
                       double rhstt[NDISC], double ai[NDISC],
                       double bi[NDISC], double ci[NDISC],
                       double wcnd[NDISC], double wdf[NDISC],
                       double ddz[NDISC], double *qdrain_m_per_s,
                       double interface_q_m_per_s[NDISC])
{
    double zsoil[NDISC];
    double denom[NDISC];
    double dsmdz[NDISC];
    double wflux[NDISC];
    int k;
    double z = 0.0;

    for (k = 0; k < ndisc; k++) {
        z += geom->dz[k];
        zsoil[k] = -z; /* Noah-MP ZSOIL is negative downward. */
        noahmp_wdfcnd1(par, theta[k], &wdf[k], &wcnd[k]);
    }

    for (k = 0; k < ndisc; k++) {
        if (k == 0) {
            double temp1 = -zsoil[1];
            denom[k] = -zsoil[k];
            ddz[k] = 2.0 / temp1;
            dsmdz[k] = 2.0 * (theta[k] - theta[k + 1]) / temp1;
            interface_q_m_per_s[k] = wdf[k] * dsmdz[k] + wcnd[k];
            wflux[k] = interface_q_m_per_s[k] - pddum_m_per_s
                     + etrani_m_per_s[k] + qseva_m_per_s;
        } else if (k < ndisc - 1) {
            double temp1 = zsoil[k - 1] - zsoil[k + 1];
            denom[k] = zsoil[k - 1] - zsoil[k];
            ddz[k] = 2.0 / temp1;
            dsmdz[k] = 2.0 * (theta[k] - theta[k + 1]) / temp1;
            interface_q_m_per_s[k] = wdf[k] * dsmdz[k] + wcnd[k];
            wflux[k] = interface_q_m_per_s[k] - interface_q_m_per_s[k - 1]
                     + etrani_m_per_s[k];
        } else {
            double qdrain = par->perc_limiter_0_to_1 * wcnd[k];
            denom[k] = zsoil[k - 1] - zsoil[k];

            if (ctrl->apply_fc_perc_threshold) {
                double available_m = (theta[k] - par->theta_fc) * geom->dz[k];
                double max_qdrain;
                if (available_m <= 0.0) {
                    qdrain = 0.0;
                } else {
                    max_qdrain = available_m / dtfine_s;
                    if (qdrain > max_qdrain) qdrain = max_qdrain;
                }
            }

            *qdrain_m_per_s = qdrain;
            interface_q_m_per_s[k] = *qdrain_m_per_s;
            wflux[k] = -interface_q_m_per_s[k - 1]
                     + etrani_m_per_s[k] + *qdrain_m_per_s;
        }
    }

    for (k = 0; k < ndisc; k++) {
        if (k == 0) {
            ai[k] = 0.0;
            bi[k] = wdf[k] * ddz[k] / denom[k];
            ci[k] = -bi[k];
        } else if (k < ndisc - 1) {
            ai[k] = -wdf[k - 1] * ddz[k - 1] / denom[k];
            ci[k] = -wdf[k] * ddz[k] / denom[k];
            bi[k] = -(ai[k] + ci[k]);
        } else {
            ai[k] = -wdf[k - 1] * ddz[k - 1] / denom[k];
            ci[k] = 0.0;
            bi[k] = -ai[k];
        }
        rhstt[k] = wflux[k] / (-denom[k]);
    }
}

/* Soil-only SSTEP translation.  Returns saturation excess leaving the top
 * and any irrecoverable bottom-layer minimum-water deficit.
 */
static int noahmp_sstep(const SoilGeometry *geom, const SoilParameters *par,
                        double dt_s, double theta[NDISC], int ndisc,
                        double ai[NDISC], double bi[NDISC], double ci[NDISC],
                        double rhstt[NDISC], double delta_theta[NDISC],
                        double *wplus_top_m, double *wminus_bottom_m)
{
    double a[NDISC], b[NDISC], c[NDISC], d[NDISC], solution[NDISC];
    int k;

    *wplus_top_m = 0.0;
    *wminus_bottom_m = 0.0;

    for (k = 0; k < ndisc; k++) {
        d[k] = rhstt[k] * dt_s;
        a[k] = ai[k] * dt_s;
        b[k] = 1.0 + bi[k] * dt_s;
        c[k] = ci[k] * dt_s;
    }

    if (noahmp_rosr12(solution, a, b, c, d, ndisc) != 0) return 1;
    for (k = 0; k < ndisc; k++) {
        delta_theta[k] = solution[k];
        theta[k] += solution[k];
    }

    /* Noah-MP SSTEP: first move supersaturation upward from bottom to top. */
    for (k = ndisc - 1; k >= 1; k--) {
        double epore = par->theta_sat;
        double wplus = fmax(theta[k] - epore, 0.0) * geom->dz[k];
        if (theta[k] > epore) theta[k] = epore;
        theta[k - 1] += wplus / geom->dz[k - 1];
    }

    *wplus_top_m = fmax(theta[0] - par->theta_sat, 0.0) * geom->dz[0];
    if (theta[0] > par->theta_sat) theta[0] = par->theta_sat;

    /* If top overflow occurred, Noah-MP then propagates any newly created
     * supersaturation downward. */
    if (*wplus_top_m > 0.0) {
        theta[1] += *wplus_top_m / geom->dz[1];
        for (k = 1; k < ndisc - 1; k++) {
            double wplus = fmax(theta[k] - par->theta_sat, 0.0) * geom->dz[k];
            if (theta[k] > par->theta_sat) theta[k] = par->theta_sat;
            theta[k + 1] += wplus / geom->dz[k + 1];
        }
        *wplus_top_m = fmax(theta[ndisc - 1] - par->theta_sat, 0.0)
                     * geom->dz[ndisc - 1];
        if (theta[ndisc - 1] > par->theta_sat) theta[ndisc - 1] = par->theta_sat;
    }

    /* Noah-MP SSTEP performs the 0.01-mm minimum-water correction only
     * if the Richards update/redistribution has made at least one layer
     * negative (IF (ANY(SH2O < 0.0))). */
    {
        int any_negative = 0;
        for (k = 0; k < ndisc; k++) {
            if (theta[k] < 0.0) {
                any_negative = 1;
                break;
            }
        }

        if (any_negative) {
            for (k = 0; k < ndisc - 1; k++) {
                double watmin = 0.00001 / geom->dz[k];
                double wminus = fmax((watmin - theta[k]) * geom->dz[k], 0.0);
                if (theta[k] < watmin) theta[k] = watmin;
                theta[k + 1] -= wminus / geom->dz[k + 1];
            }
            {
                double watmin = 0.00001 / geom->dz[ndisc - 1];
                *wminus_bottom_m = fmax((watmin - theta[ndisc - 1])
                                        * geom->dz[ndisc - 1], 0.0);
                if (theta[ndisc - 1] < watmin) theta[ndisc - 1] = watmin;
            }
        }
    }

    return 0;
}

static void comparison_et_rates(const SoilControl *ctrl, const SoilGeometry *geom,
                                const SoilParameters *par, const double theta[NDISC],
                                double pet_m_per_s, double dtfine_s,
                                double etrani_m_per_s[NDISC])
{
    int nroot = ctrl->deepest_root_disc;
    double denom = par->theta_aet_eq_pet - par->theta_wp;
    int k;

    if (nroot < 1) nroot = 1;
    if (nroot > ctrl->ndisc) nroot = ctrl->ndisc;
    if (denom < 1.0e-12) denom = 1.0e-12;

    for (k = 0; k < ctrl->ndisc; k++) etrani_m_per_s[k] = 0.0;
    for (k = 0; k < nroot; k++) {
        double f_aet;
        double demand;
        double available_rate;
        if (theta[k] <= par->theta_wp) f_aet = 0.0;
        else if (theta[k] >= par->theta_aet_eq_pet) f_aet = 1.0;
        else f_aet = (theta[k] - par->theta_wp) / denom;

        demand = pet_m_per_s * f_aet / (double)nroot;
        available_rate = fmax(theta[k] - par->theta_wp, 0.0) * geom->dz[k]
                       / dtfine_s;
        etrani_m_per_s[k] = fmin(demand, available_rate);
    }
}

int noahmp_soil_step_one_hour_stateless(
    const SoilControl        *ctrl,
    const SoilGeometry       *geom,
    const SoilParameters     *par,
    const SoilStateIn        *sin,
    const SoilForcing        *forcing,
    SoilStateOut             *sout,
    SoilFluxes               *flux,
    TimestepSoilMassbal      *mb,
    FILE                     *debug_fptr)
{
    double theta[NDISC];
    double storage_start, storage_end;
    double rain_m_per_s, pet_m_per_s;
    double dt_s, dtfine_s;
    int niter = 3;
    int ndisc;
    int iter, k;
    double total_saturation_excess_m = 0.0;
    double total_bottom_deficit_m = 0.0;

    (void)debug_fptr;

    if (!ctrl || !geom || !par || !sin || !forcing || !sout || !flux || !mb) return 1;
    ndisc = ctrl->ndisc;
    if (ndisc != NDISC || ndisc < 2) return 2;

    memset(flux, 0, sizeof(*flux));
    memset(mb, 0, sizeof(*mb));
    for (k = 0; k < ndisc; k++) {
        theta[k] = sin->theta_in[k];
        sout->ch_lut_hint_out[k] = sin->ch_lut_hint_in[k];
    }

    storage_start = storage_sum(theta, geom->dz, ndisc);
    dt_s = ctrl->dt_hours * 3600.0;
    rain_m_per_s = (forcing->rain_mm_per_h / 1000.0) / 3600.0;
    pet_m_per_s = (forcing->pet_mm_per_h / 1000.0) / 3600.0;

    /* Supplied SOILWATER: NITER=3, doubled if PDDUM*DT exceeds saturated
     * storage of layer 1.  Here PDDUM is incident rainfall for the isolated
     * solver comparison. */
    if (rain_m_per_s * dt_s > geom->dz[0] * par->theta_sat) niter *= 2;
    dtfine_s = dt_s / (double)niter;
    flux->n_sub_used = niter;

    for (iter = 0; iter < niter; iter++) {
        double etrani[NDISC];
        double rhstt[NDISC], ai[NDISC], bi[NDISC], ci[NDISC];
        double wcnd[NDISC], wdf[NDISC], ddz[NDISC], qdrain = 0.0;
        double interface_q[NDISC];
        double delta_theta[NDISC];
        double wplus = 0.0, wminus = 0.0;
        double storage_before = storage_sum(theta, geom->dz, ndisc);
        double et_iter_m = 0.0;

        comparison_et_rates(ctrl, geom, par, theta, pet_m_per_s, dtfine_s, etrani);

        noahmp_srt(ctrl, geom, par, theta, etrani,
                   rain_m_per_s, 0.0, dtfine_s, ndisc,
                   rhstt, ai, bi, ci, wcnd, wdf, ddz, &qdrain, interface_q);

        for (k = 0; k < ndisc; k++) {
            et_iter_m += etrani[k] * dtfine_s;
            flux->AET_by_disc_m[k] += etrani[k] * dtfine_s;
        }

        if (noahmp_sstep(geom, par, dtfine_s, theta, ndisc,
                         ai, bi, ci, rhstt, delta_theta,
                         &wplus, &wminus) != 0) return 3;

        /* SRT's interface_q[] is evaluated from the state at the beginning
         * of the fine step.  The implicit Richards solve linearizes only the
         * diffusivity term, so reconstruct the flux actually represented by
         * the solved system using the ROSR12 moisture increments.
         *
         * q_i(new) = q_i(old)
         *          + WDF_i * DDZ_i * (delta_theta_i-delta_theta_{i+1})
         *
         * Noah-MP does not linearize the conductivity term here.  The bottom
         * free-drainage flux is likewise held at the SRT value for this fine
         * step.  Subsequent SSTEP saturation redistribution is a separate
         * correction and is not folded into these Richards interface fluxes. */
        for (k = 0; k < ndisc - 1; k++) {
            double implicit_q = interface_q[k]
                              + wdf[k] * ddz[k]
                              * (delta_theta[k] - delta_theta[k + 1]);
            flux->interface_vol_m[k] += implicit_q * dtfine_s;
        }
        flux->interface_vol_m[ndisc - 1] += qdrain * dtfine_s;
        flux->percolation_to_gw_m += qdrain * dtfine_s;

        total_saturation_excess_m += wplus;
        total_bottom_deficit_m += wminus;
        mb->AET_m += et_iter_m;

        /* Diagnostic check only; final mass balance is calculated below. */
        (void)storage_before;
    }

    for (k = 0; k < ndisc; k++) {
        sout->theta_out[k] = theta[k];
        flux->interface_rate_m_per_h[k] = flux->interface_vol_m[k]
                                        / ctrl->dt_hours;
    }

    flux->rain_excess_m = total_saturation_excess_m;
    flux->rain_into_soil_m = rain_m_per_s * dt_s - flux->rain_excess_m;
    if (flux->rain_into_soil_m < 0.0) flux->rain_into_soil_m = 0.0;

    storage_end = storage_sum(theta, geom->dz, ndisc);
    mb->in_rain_m = flux->rain_into_soil_m;
    mb->excess_m = flux->rain_excess_m;
    mb->perc_m = flux->percolation_to_gw_m;
    mb->lateral_m = 0.0;
    mb->delta_storage_m = storage_end - storage_start;

    /* WMINUS is water Noah-MP must obtain from subsurface runoff to repair a
     * negative bottom state.  Report it as a mass-balance correction rather
     * than silently hiding it.  It should be zero in normal comparison runs. */
    mb->residual_m = mb->in_rain_m + total_bottom_deficit_m
                   - (mb->perc_m + mb->AET_m + mb->lateral_m)
                   - mb->delta_storage_m;

    return 0;
}
